# -*- coding: utf-8 -*-
"""bithumb_tradeProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hg3SXyOshyK8dUjNCUOQjP7a2Ep5bDQD
"""

import requests

url = "https://api.bithumb.com/v1/market/all?isDetails=false"

headers = {"accept": "application/json"}

response = requests.get(url, headers=headers)

print(response.text)

import requests

url = "https://api.bithumb.com/v1/candles/minutes/1?market=KRW-BTC&count=1"

headers = {"accept": "application/json"}

response = requests.get(url, headers=headers)

print(response.text)

import requests

url = "https://api.bithumb.com/v1/ticker?markets=KRW-BTC"

headers = {"accept": "application/json"}

response = requests.get(url, headers=headers)

print(response.text)

# Python 3
# pip3 installl pyJwt
import jwt
import uuid
import time
import requests

# Set API parameters
accessKey = '발급받은 API KEY'
secretKey = '발급받은 SECRET KEY'
apiUrl = 'https://api.bithumb.com'

# Generate access token
payload = {
    'access_key': accessKey,
    'nonce': str(uuid.uuid4()),
    'timestamp': round(time.time() * 1000)
}
jwt_token = jwt.encode(payload, secretKey)
authorization_token = 'Bearer {}'.format(jwt_token)
headers = {
  'Authorization': authorization_token
}

try:
    # Call API
    response = requests.get(apiUrl + '/v1/accounts', headers=headers)
    # handle to success or fail
    print(response.status_code)
    print(response.json())
except Exception as err:
    # handle exception
    print(err)



